name: Compile and Execute

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Execute, and Archive
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install C++ compiler
    - name: Install C++ Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    # Compile and execute C++ files
    - name: Compile and Execute C++ files
      run: |
        mkdir -p build/cpp
        for file in $(find . -name "*.cpp"); do
          g++ $file -o build/cpp/$(basename $file .cpp)
          ./build/cpp/$(basename $file .cpp)
        done

    # Install .NET SDK for C# compilation
    - name: Install .NET SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0

    # Compile and execute C# files
    - name: Compile and Execute C# files
      run: |
        mkdir -p build/cs
        for file in $(find . -name "*.cs"); do
          dotnet build $file -o build/cs
          dotnet run --project $file
        done

    # Install Kotlin compiler
    - name: Install Kotlin Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk
        curl -s https://get.sdkman.io | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install kotlin

    # Compile and execute Kotlin files
    - name: Compile and Execute Kotlin files
      run: |
        mkdir -p build/kotlin
        for file in $(find . -name "*.kt"); do
          kotlinc $file -include-runtime -d build/kotlin/$(basename $file .kt).jar
          java -jar build/kotlin/$(basename $file .kt).jar
        done